###############################################################################

#' Visulization of components distance / dissimilarity in k dimension.
#'
#' @import ggplot2
#' @param x An object of `mina` with list @dmr defined.
#' @param match The column name of the components IDs in @des with exactly the
#' same as rownames in x.
#' @param color The column name in @des to be used for different color groups.
#' @param (optional) shape The column name in @des to be used for different
#' shape groups.
#' @return p The plotted figure.
#' @examples
#' p <- com_plot(x, match = "Sample_ID", color = "Compartment",
#'               shape = "Soil")
#' @exportMethod com_plot

setMethod("com_plot", signature("mina", "ANY", "ANY", "ANY"),
          function(x, match, color, shape) {
              stop("Mush specify a `match` column.")
          }
)

setMethod("com_plot", signature("mina", "character", "ANY", "ANY"),
          function(x, match, color, shape) {
              stop("Mush specify a column for `color`.")
          }
)

setMethod("com_plot", signature("mina", "character", "character", "ANY"),
          function(x, match, color, shape = NULL) {
              p <- pcoa_plot(x@dmr, x@des_tab, match = match, color = color,
                            shape = shape)
              return(p)
          }
)


###############################################################################

#' Visulization of components distance / dissimilarity in k dimension.
#'
#' @import ggplot2
#' @param x An list generated by `dmr`.
#' @param des The corresponding descriptive table.
#' @param match The column name of the components IDs in `des` with exactly the
#' same as rownames in x.
#' @param color The column name in `des` to be used for different color groups.
#' @param (optional) shape The column name in `des` to be used for different
#' shape groups.
#' @return p The plotted figure.
#' @examples
#' p <- pcoa_plot(x, des, match = "Sample_ID", color = "Compartment",
#'               shape = "Soil")
#' @export

pcoa_plot <- function(x, des, match, color, shape = NULL) {
    points <- x$points
    if (nrow(points) != nrow(des)) {
        stop("Component number in `dmr` and `des` are different!")
    }
    if (all(sort(rownames(points)) != sort(des[[match]]))) {
        stop("Component IDs in `dmr` and `des` are different!")
    }

    # finish checking and start plotting
    points <- as.data.frame(points)
    colnames(points) <- c("x", "y")

    des <- des[match(rownames(points), des[[match]]), ]
    points <- cbind(points, des[[color]])
    colnames(points)[ncol(points)] <- color
    if (! is.null(shape)) {
        points <- cbind(points, des[[shape]])
        colnames(points)[ncol(points)] <- shape
    }

    eig <- x$eig
    eig[eig < 0] <- 0
    eig1 <- 100 * eig[1] / sum(eig)
    eig2 <- 100 * eig[2] / sum(eig)

    p <- ggplot(points, aes_string(x = "x", y = "y", color = color,
                                   shape = shape)) +
                geom_point(size = 1.2, alpha = 0.8) +
                labs (x = paste0("PCo1 (", format(eig1, digits = 4), "%)"),
                      y = paste0("PCo2 (", format(eig2, digits = 4), "%)")) +
                theme(panel.background = element_blank(),
                      panel.grid = element_blank(),
                      axis.line.x = element_line(color = "black"),
                      axis.line.y = element_line(color = "black"),
                      axis.ticks = element_line(color = "black"),
                      axis.text = element_text(colour = "black", size = 10),
                      legend.position = "right",
                      legend.background = element_blank(),
                      legend.key = element_blank(),
                      text = element_text(family="sans")
                )
    return(p)
}
